version: '2'
services:
    jhipstersampleapplicationonlinetoolstest-app:
        image: jhipstersampleapplicationonlinetoolstest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplicationonlinetoolstest-mysql:3306/jhipstersampleapplicationonlinetoolstest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8082:8082
    jhipstersampleapplicationonlinetoolstest-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplicationonlinetoolstest-mysql
